# This file is for render site varibles and plugins
# don't remove this file.
# The presence of this file is for compatibility with Blogdown and Forestry.
#
# The actual configuration files are stored in the `config/_default/` folder.


######################### site variables ##############################
# customize your color and font from here.
[params.variables]
color_primary = "#dc6f6e"
color_secondary = "#fbf9f8"
body_color = "#fbf9f8"
text_color = "#777"
text_dark = "#1E2740"
text_light = "#666666"
border_color = "#E8E8E8"
dark_body_color = "#051b29"
dark_text_color = "#cbcbcb"
dark_text_light = "#bbbbbb"
dark_text_dark = "#fff"
dark_border_color = "#283e4b"
black = "#000"
white = "#fff"
dark = "#222"
light = "#fdfdfd"

# font variables
# base font size for full website, 
font_size = "16px" # default is 16px

# Font Scale Sizes
# "minorSecond": 1.067,
# "majorSecond": 1.125,
# "minorThird": 1.2,
# "majorThird": 1.25,
# "perfectFourth": 1.333,
# "augmentedFourth": 1.414,
# "perfectFifth": 1.5,
# "goldenRatio": 1.618
font_scale = "1.25" # default is "majorThird": 1.25

# go to https://fonts.google.com/ to find the font you want to use. select your font and copy only the bold part from the URL. and paste it here.
# example: "Work+Sans:wght@400;500;600"
font_primary = "Poppins:wght@400;500;600" 
font_primary_type = "sans-serif"      # [serif/sans-serif]
font_secondary = ""
font_secondary_type = ""              # [serif/sans-serif]
font_icon = "Font Awesome 6 Free"     # https://fontawesome.com/v6/icons


############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/font-awesome/v6/brands.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/solid.css"
[[params.plugins.css]]
link = "plugins/font-awesome/v6/icons.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/webfont/webfont-loader-2.js"
# [[params.plugins.js]]
# link = "plugins/glightbox.js"
# [[params.plugins.js]]
# link = "plugins/lazy-loader.js"
# [[params.plugins.js]]
# link = "https://cpwebassets.codepen.io/assets/embed/ei.js"
# attributes = "async"

[module]
[module.hugoVersion]
  extended = true
  min = "0.106.0"

[[module.imports]]
path = "github.com/gohugoio/hugo-mod-bootstrap-scss/v5"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/components/preloader"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/components/custom-script"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/components/render-link"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/icons/font-awesome"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/pwa"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/images"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/buttons"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/codepen"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/collapse"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/notice"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/video"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/tabs"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/image"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/gallery"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/table-of-contents"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/youtube-lite"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/shortcodes/vimeo-lite"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/baidu-analytics"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/matomo-analytics"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/plausible-analytics"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/counter-analytics"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/google-tag-manager"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/site-verifications"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/seo-tools/basic-seo"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/gzip-caching"

[[module.imports]]
path = "github.com/gethugothemes/hugo-modules/adsense"
